namespace Bunifu
{
    partial class SetupMoneyWife
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SetupMoneyWife));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn1tr = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn5tr = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn50tr = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn100tr = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtCash = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtBank = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnBackToRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnDone = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 24F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(44, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(336, 45);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "Setup your MoneyWife";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btn1tr
            // 
            this.btn1tr.AllowAnimations = true;
            this.btn1tr.AllowMouseEffects = true;
            this.btn1tr.AllowToggling = false;
            this.btn1tr.AnimationSpeed = 200;
            this.btn1tr.AutoGenerateColors = false;
            this.btn1tr.AutoRoundBorders = false;
            this.btn1tr.AutoSizeLeftIcon = true;
            this.btn1tr.AutoSizeRightIcon = true;
            this.btn1tr.BackColor = System.Drawing.Color.Transparent;
            this.btn1tr.BackColor1 = System.Drawing.Color.DarkGray;
            this.btn1tr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn1tr.BackgroundImage")));
            this.btn1tr.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn1tr.ButtonText = "1 triệu";
            this.btn1tr.ButtonTextMarginLeft = 0;
            this.btn1tr.ColorContrastOnClick = 45;
            this.btn1tr.ColorContrastOnHover = 45;
            this.btn1tr.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn1tr.CustomizableEdges = borderEdges7;
            this.btn1tr.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn1tr.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn1tr.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn1tr.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn1tr.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn1tr.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn1tr.ForeColor = System.Drawing.Color.White;
            this.btn1tr.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn1tr.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn1tr.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn1tr.IconMarginLeft = 11;
            this.btn1tr.IconPadding = 10;
            this.btn1tr.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn1tr.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn1tr.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn1tr.IconSize = 25;
            this.btn1tr.IdleBorderColor = System.Drawing.Color.DimGray;
            this.btn1tr.IdleBorderRadius = 20;
            this.btn1tr.IdleBorderThickness = 1;
            this.btn1tr.IdleFillColor = System.Drawing.Color.DarkGray;
            this.btn1tr.IdleIconLeftImage = null;
            this.btn1tr.IdleIconRightImage = null;
            this.btn1tr.IndicateFocus = false;
            this.btn1tr.Location = new System.Drawing.Point(12, 63);
            this.btn1tr.Name = "btn1tr";
            this.btn1tr.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn1tr.OnDisabledState.BorderRadius = 20;
            this.btn1tr.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn1tr.OnDisabledState.BorderThickness = 1;
            this.btn1tr.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn1tr.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn1tr.OnDisabledState.IconLeftImage = null;
            this.btn1tr.OnDisabledState.IconRightImage = null;
            this.btn1tr.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn1tr.onHoverState.BorderRadius = 20;
            this.btn1tr.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn1tr.onHoverState.BorderThickness = 1;
            this.btn1tr.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn1tr.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn1tr.onHoverState.IconLeftImage = null;
            this.btn1tr.onHoverState.IconRightImage = null;
            this.btn1tr.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.btn1tr.OnIdleState.BorderRadius = 20;
            this.btn1tr.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn1tr.OnIdleState.BorderThickness = 1;
            this.btn1tr.OnIdleState.FillColor = System.Drawing.Color.DarkGray;
            this.btn1tr.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn1tr.OnIdleState.IconLeftImage = null;
            this.btn1tr.OnIdleState.IconRightImage = null;
            this.btn1tr.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn1tr.OnPressedState.BorderRadius = 20;
            this.btn1tr.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn1tr.OnPressedState.BorderThickness = 1;
            this.btn1tr.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn1tr.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn1tr.OnPressedState.IconLeftImage = null;
            this.btn1tr.OnPressedState.IconRightImage = null;
            this.btn1tr.Size = new System.Drawing.Size(123, 40);
            this.btn1tr.TabIndex = 5;
            this.btn1tr.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn1tr.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn1tr.TextMarginLeft = 0;
            this.btn1tr.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn1tr.UseDefaultRadiusAndThickness = true;
            // 
            // btn5tr
            // 
            this.btn5tr.AllowAnimations = true;
            this.btn5tr.AllowMouseEffects = true;
            this.btn5tr.AllowToggling = false;
            this.btn5tr.AnimationSpeed = 200;
            this.btn5tr.AutoGenerateColors = false;
            this.btn5tr.AutoRoundBorders = false;
            this.btn5tr.AutoSizeLeftIcon = true;
            this.btn5tr.AutoSizeRightIcon = true;
            this.btn5tr.BackColor = System.Drawing.Color.Transparent;
            this.btn5tr.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn5tr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn5tr.BackgroundImage")));
            this.btn5tr.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5tr.ButtonText = "5 triệu";
            this.btn5tr.ButtonTextMarginLeft = 0;
            this.btn5tr.ColorContrastOnClick = 45;
            this.btn5tr.ColorContrastOnHover = 45;
            this.btn5tr.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn5tr.CustomizableEdges = borderEdges8;
            this.btn5tr.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn5tr.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn5tr.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn5tr.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn5tr.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn5tr.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn5tr.ForeColor = System.Drawing.Color.White;
            this.btn5tr.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn5tr.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn5tr.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn5tr.IconMarginLeft = 11;
            this.btn5tr.IconPadding = 10;
            this.btn5tr.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn5tr.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn5tr.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn5tr.IconSize = 25;
            this.btn5tr.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btn5tr.IdleBorderRadius = 20;
            this.btn5tr.IdleBorderThickness = 1;
            this.btn5tr.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn5tr.IdleIconLeftImage = null;
            this.btn5tr.IdleIconRightImage = null;
            this.btn5tr.IndicateFocus = false;
            this.btn5tr.Location = new System.Drawing.Point(141, 63);
            this.btn5tr.Name = "btn5tr";
            this.btn5tr.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn5tr.OnDisabledState.BorderRadius = 20;
            this.btn5tr.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5tr.OnDisabledState.BorderThickness = 1;
            this.btn5tr.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn5tr.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn5tr.OnDisabledState.IconLeftImage = null;
            this.btn5tr.OnDisabledState.IconRightImage = null;
            this.btn5tr.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn5tr.onHoverState.BorderRadius = 20;
            this.btn5tr.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5tr.onHoverState.BorderThickness = 1;
            this.btn5tr.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn5tr.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn5tr.onHoverState.IconLeftImage = null;
            this.btn5tr.onHoverState.IconRightImage = null;
            this.btn5tr.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btn5tr.OnIdleState.BorderRadius = 20;
            this.btn5tr.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5tr.OnIdleState.BorderThickness = 1;
            this.btn5tr.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn5tr.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn5tr.OnIdleState.IconLeftImage = null;
            this.btn5tr.OnIdleState.IconRightImage = null;
            this.btn5tr.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn5tr.OnPressedState.BorderRadius = 20;
            this.btn5tr.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5tr.OnPressedState.BorderThickness = 1;
            this.btn5tr.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn5tr.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn5tr.OnPressedState.IconLeftImage = null;
            this.btn5tr.OnPressedState.IconRightImage = null;
            this.btn5tr.Size = new System.Drawing.Size(140, 40);
            this.btn5tr.TabIndex = 6;
            this.btn5tr.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn5tr.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn5tr.TextMarginLeft = 0;
            this.btn5tr.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn5tr.UseDefaultRadiusAndThickness = true;
            // 
            // btn50tr
            // 
            this.btn50tr.AllowAnimations = true;
            this.btn50tr.AllowMouseEffects = true;
            this.btn50tr.AllowToggling = false;
            this.btn50tr.AnimationSpeed = 200;
            this.btn50tr.AutoGenerateColors = false;
            this.btn50tr.AutoRoundBorders = false;
            this.btn50tr.AutoSizeLeftIcon = true;
            this.btn50tr.AutoSizeRightIcon = true;
            this.btn50tr.BackColor = System.Drawing.Color.Transparent;
            this.btn50tr.BackColor1 = System.Drawing.Color.SeaGreen;
            this.btn50tr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn50tr.BackgroundImage")));
            this.btn50tr.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50tr.ButtonText = "50 triệu";
            this.btn50tr.ButtonTextMarginLeft = 0;
            this.btn50tr.ColorContrastOnClick = 45;
            this.btn50tr.ColorContrastOnHover = 45;
            this.btn50tr.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btn50tr.CustomizableEdges = borderEdges9;
            this.btn50tr.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn50tr.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn50tr.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn50tr.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn50tr.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn50tr.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn50tr.ForeColor = System.Drawing.Color.White;
            this.btn50tr.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn50tr.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn50tr.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn50tr.IconMarginLeft = 11;
            this.btn50tr.IconPadding = 10;
            this.btn50tr.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn50tr.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn50tr.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn50tr.IconSize = 25;
            this.btn50tr.IdleBorderColor = System.Drawing.Color.MediumSeaGreen;
            this.btn50tr.IdleBorderRadius = 20;
            this.btn50tr.IdleBorderThickness = 1;
            this.btn50tr.IdleFillColor = System.Drawing.Color.SeaGreen;
            this.btn50tr.IdleIconLeftImage = null;
            this.btn50tr.IdleIconRightImage = null;
            this.btn50tr.IndicateFocus = false;
            this.btn50tr.Location = new System.Drawing.Point(287, 63);
            this.btn50tr.Name = "btn50tr";
            this.btn50tr.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn50tr.OnDisabledState.BorderRadius = 20;
            this.btn50tr.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50tr.OnDisabledState.BorderThickness = 1;
            this.btn50tr.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn50tr.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn50tr.OnDisabledState.IconLeftImage = null;
            this.btn50tr.OnDisabledState.IconRightImage = null;
            this.btn50tr.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn50tr.onHoverState.BorderRadius = 20;
            this.btn50tr.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50tr.onHoverState.BorderThickness = 1;
            this.btn50tr.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn50tr.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn50tr.onHoverState.IconLeftImage = null;
            this.btn50tr.onHoverState.IconRightImage = null;
            this.btn50tr.OnIdleState.BorderColor = System.Drawing.Color.MediumSeaGreen;
            this.btn50tr.OnIdleState.BorderRadius = 20;
            this.btn50tr.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50tr.OnIdleState.BorderThickness = 1;
            this.btn50tr.OnIdleState.FillColor = System.Drawing.Color.SeaGreen;
            this.btn50tr.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn50tr.OnIdleState.IconLeftImage = null;
            this.btn50tr.OnIdleState.IconRightImage = null;
            this.btn50tr.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn50tr.OnPressedState.BorderRadius = 20;
            this.btn50tr.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50tr.OnPressedState.BorderThickness = 1;
            this.btn50tr.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn50tr.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn50tr.OnPressedState.IconLeftImage = null;
            this.btn50tr.OnPressedState.IconRightImage = null;
            this.btn50tr.Size = new System.Drawing.Size(150, 40);
            this.btn50tr.TabIndex = 7;
            this.btn50tr.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn50tr.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn50tr.TextMarginLeft = 0;
            this.btn50tr.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn50tr.UseDefaultRadiusAndThickness = true;
            // 
            // btn100tr
            // 
            this.btn100tr.AllowAnimations = true;
            this.btn100tr.AllowMouseEffects = true;
            this.btn100tr.AllowToggling = false;
            this.btn100tr.AnimationSpeed = 200;
            this.btn100tr.AutoGenerateColors = false;
            this.btn100tr.AutoRoundBorders = false;
            this.btn100tr.AutoSizeLeftIcon = true;
            this.btn100tr.AutoSizeRightIcon = true;
            this.btn100tr.BackColor = System.Drawing.Color.Transparent;
            this.btn100tr.BackColor1 = System.Drawing.Color.Crimson;
            this.btn100tr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn100tr.BackgroundImage")));
            this.btn100tr.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100tr.ButtonText = "100 triệu";
            this.btn100tr.ButtonTextMarginLeft = 0;
            this.btn100tr.ColorContrastOnClick = 45;
            this.btn100tr.ColorContrastOnHover = 45;
            this.btn100tr.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btn100tr.CustomizableEdges = borderEdges10;
            this.btn100tr.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn100tr.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn100tr.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn100tr.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn100tr.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn100tr.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn100tr.ForeColor = System.Drawing.Color.White;
            this.btn100tr.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn100tr.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn100tr.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn100tr.IconMarginLeft = 11;
            this.btn100tr.IconPadding = 10;
            this.btn100tr.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn100tr.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn100tr.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn100tr.IconSize = 25;
            this.btn100tr.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btn100tr.IdleBorderRadius = 20;
            this.btn100tr.IdleBorderThickness = 1;
            this.btn100tr.IdleFillColor = System.Drawing.Color.Crimson;
            this.btn100tr.IdleIconLeftImage = null;
            this.btn100tr.IdleIconRightImage = null;
            this.btn100tr.IndicateFocus = false;
            this.btn100tr.Location = new System.Drawing.Point(443, 63);
            this.btn100tr.Name = "btn100tr";
            this.btn100tr.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn100tr.OnDisabledState.BorderRadius = 20;
            this.btn100tr.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100tr.OnDisabledState.BorderThickness = 1;
            this.btn100tr.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn100tr.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn100tr.OnDisabledState.IconLeftImage = null;
            this.btn100tr.OnDisabledState.IconRightImage = null;
            this.btn100tr.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn100tr.onHoverState.BorderRadius = 20;
            this.btn100tr.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100tr.onHoverState.BorderThickness = 1;
            this.btn100tr.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn100tr.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn100tr.onHoverState.IconLeftImage = null;
            this.btn100tr.onHoverState.IconRightImage = null;
            this.btn100tr.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btn100tr.OnIdleState.BorderRadius = 20;
            this.btn100tr.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100tr.OnIdleState.BorderThickness = 1;
            this.btn100tr.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btn100tr.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn100tr.OnIdleState.IconLeftImage = null;
            this.btn100tr.OnIdleState.IconRightImage = null;
            this.btn100tr.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn100tr.OnPressedState.BorderRadius = 20;
            this.btn100tr.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100tr.OnPressedState.BorderThickness = 1;
            this.btn100tr.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn100tr.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn100tr.OnPressedState.IconLeftImage = null;
            this.btn100tr.OnPressedState.IconRightImage = null;
            this.btn100tr.Size = new System.Drawing.Size(160, 40);
            this.btn100tr.TabIndex = 8;
            this.btn100tr.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn100tr.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn100tr.TextMarginLeft = 0;
            this.btn100tr.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn100tr.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(92, 141);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(108, 21);
            this.bunifuLabel2.TabIndex = 9;
            this.bunifuLabel2.Text = "Tiền mặt/Cash:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.Location = new System.Drawing.Point(85, 203);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(115, 21);
            this.bunifuLabel3.TabIndex = 10;
            this.bunifuLabel3.Text = "Tài khoản/Bank:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtCash
            // 
            this.txtCash.AcceptsReturn = false;
            this.txtCash.AcceptsTab = false;
            this.txtCash.AnimationSpeed = 200;
            this.txtCash.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCash.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCash.AutoSizeHeight = true;
            this.txtCash.BackColor = System.Drawing.Color.Transparent;
            this.txtCash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCash.BackgroundImage")));
            this.txtCash.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCash.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCash.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCash.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCash.BorderRadius = 20;
            this.txtCash.BorderThickness = 1;
            this.txtCash.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCash.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCash.DefaultText = "";
            this.txtCash.FillColor = System.Drawing.Color.White;
            this.txtCash.HideSelection = true;
            this.txtCash.IconLeft = null;
            this.txtCash.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.IconPadding = 10;
            this.txtCash.IconRight = null;
            this.txtCash.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.Lines = new string[0];
            this.txtCash.Location = new System.Drawing.Point(206, 125);
            this.txtCash.MaxLength = 32767;
            this.txtCash.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCash.Modified = false;
            this.txtCash.Multiline = false;
            this.txtCash.Name = "txtCash";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCash.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnIdleState = stateProperties16;
            this.txtCash.Padding = new System.Windows.Forms.Padding(3);
            this.txtCash.PasswordChar = '\0';
            this.txtCash.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCash.PlaceholderText = "000.000";
            this.txtCash.ReadOnly = false;
            this.txtCash.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCash.SelectedText = "";
            this.txtCash.SelectionLength = 0;
            this.txtCash.SelectionStart = 0;
            this.txtCash.ShortcutsEnabled = true;
            this.txtCash.Size = new System.Drawing.Size(289, 37);
            this.txtCash.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCash.TabIndex = 12;
            this.txtCash.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtCash.TextMarginBottom = 0;
            this.txtCash.TextMarginLeft = 3;
            this.txtCash.TextMarginTop = 1;
            this.txtCash.TextPlaceholder = "000.000";
            this.txtCash.UseSystemPasswordChar = false;
            this.txtCash.WordWrap = true;
            // 
            // txtBank
            // 
            this.txtBank.AcceptsReturn = false;
            this.txtBank.AcceptsTab = false;
            this.txtBank.AnimationSpeed = 200;
            this.txtBank.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBank.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBank.AutoSizeHeight = true;
            this.txtBank.BackColor = System.Drawing.Color.Transparent;
            this.txtBank.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBank.BackgroundImage")));
            this.txtBank.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtBank.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBank.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtBank.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtBank.BorderRadius = 20;
            this.txtBank.BorderThickness = 1;
            this.txtBank.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBank.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBank.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBank.DefaultText = "";
            this.txtBank.FillColor = System.Drawing.Color.White;
            this.txtBank.HideSelection = true;
            this.txtBank.IconLeft = null;
            this.txtBank.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBank.IconPadding = 10;
            this.txtBank.IconRight = null;
            this.txtBank.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBank.Lines = new string[0];
            this.txtBank.Location = new System.Drawing.Point(206, 187);
            this.txtBank.MaxLength = 32767;
            this.txtBank.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBank.Modified = false;
            this.txtBank.Multiline = false;
            this.txtBank.Name = "txtBank";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBank.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBank.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBank.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBank.OnIdleState = stateProperties20;
            this.txtBank.Padding = new System.Windows.Forms.Padding(3);
            this.txtBank.PasswordChar = '\0';
            this.txtBank.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBank.PlaceholderText = "000.000";
            this.txtBank.ReadOnly = false;
            this.txtBank.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBank.SelectedText = "";
            this.txtBank.SelectionLength = 0;
            this.txtBank.SelectionStart = 0;
            this.txtBank.ShortcutsEnabled = true;
            this.txtBank.Size = new System.Drawing.Size(289, 37);
            this.txtBank.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBank.TabIndex = 13;
            this.txtBank.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtBank.TextMarginBottom = 0;
            this.txtBank.TextMarginLeft = 3;
            this.txtBank.TextMarginTop = 1;
            this.txtBank.TextPlaceholder = "000.000";
            this.txtBank.UseSystemPasswordChar = false;
            this.txtBank.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(102, 234);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(98, 43);
            this.bunifuLabel4.TabIndex = 14;
            this.bunifuLabel4.Text = "Total money/\r\nTổng tiền:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.AutoSizeHeight = true;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 20;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(206, 240);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties24;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "000.000";
            this.bunifuTextBox1.ReadOnly = true;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(289, 37);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 15;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 1;
            this.bunifuTextBox1.TextPlaceholder = "000.000";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // btnBackToRegister
            // 
            this.btnBackToRegister.AllowAnimations = true;
            this.btnBackToRegister.AllowMouseEffects = true;
            this.btnBackToRegister.AllowToggling = false;
            this.btnBackToRegister.AnimationSpeed = 200;
            this.btnBackToRegister.AutoGenerateColors = false;
            this.btnBackToRegister.AutoRoundBorders = false;
            this.btnBackToRegister.AutoSizeLeftIcon = true;
            this.btnBackToRegister.AutoSizeRightIcon = true;
            this.btnBackToRegister.BackColor = System.Drawing.Color.Transparent;
            this.btnBackToRegister.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBackToRegister.BackgroundImage")));
            this.btnBackToRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.ButtonText = "Back";
            this.btnBackToRegister.ButtonTextMarginLeft = 0;
            this.btnBackToRegister.ColorContrastOnClick = 45;
            this.btnBackToRegister.ColorContrastOnHover = 45;
            this.btnBackToRegister.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnBackToRegister.CustomizableEdges = borderEdges11;
            this.btnBackToRegister.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBackToRegister.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBackToRegister.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBackToRegister.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBackToRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnBackToRegister.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBackToRegister.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBackToRegister.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBackToRegister.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBackToRegister.IconMarginLeft = 11;
            this.btnBackToRegister.IconPadding = 10;
            this.btnBackToRegister.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBackToRegister.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBackToRegister.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBackToRegister.IconSize = 25;
            this.btnBackToRegister.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.IdleBorderRadius = 20;
            this.btnBackToRegister.IdleBorderThickness = 1;
            this.btnBackToRegister.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.IdleIconLeftImage = null;
            this.btnBackToRegister.IdleIconRightImage = null;
            this.btnBackToRegister.IndicateFocus = false;
            this.btnBackToRegister.Location = new System.Drawing.Point(109, 310);
            this.btnBackToRegister.Name = "btnBackToRegister";
            this.btnBackToRegister.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBackToRegister.OnDisabledState.BorderRadius = 20;
            this.btnBackToRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.OnDisabledState.BorderThickness = 1;
            this.btnBackToRegister.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBackToRegister.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBackToRegister.OnDisabledState.IconLeftImage = null;
            this.btnBackToRegister.OnDisabledState.IconRightImage = null;
            this.btnBackToRegister.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBackToRegister.onHoverState.BorderRadius = 20;
            this.btnBackToRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.onHoverState.BorderThickness = 1;
            this.btnBackToRegister.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBackToRegister.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.onHoverState.IconLeftImage = null;
            this.btnBackToRegister.onHoverState.IconRightImage = null;
            this.btnBackToRegister.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.OnIdleState.BorderRadius = 20;
            this.btnBackToRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.OnIdleState.BorderThickness = 1;
            this.btnBackToRegister.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.OnIdleState.IconLeftImage = null;
            this.btnBackToRegister.OnIdleState.IconRightImage = null;
            this.btnBackToRegister.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBackToRegister.OnPressedState.BorderRadius = 20;
            this.btnBackToRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.OnPressedState.BorderThickness = 1;
            this.btnBackToRegister.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBackToRegister.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.OnPressedState.IconLeftImage = null;
            this.btnBackToRegister.OnPressedState.IconRightImage = null;
            this.btnBackToRegister.Size = new System.Drawing.Size(150, 39);
            this.btnBackToRegister.TabIndex = 25;
            this.btnBackToRegister.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBackToRegister.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBackToRegister.TextMarginLeft = 0;
            this.btnBackToRegister.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBackToRegister.UseDefaultRadiusAndThickness = true;
            // 
            // btnDone
            // 
            this.btnDone.AllowAnimations = true;
            this.btnDone.AllowMouseEffects = true;
            this.btnDone.AllowToggling = false;
            this.btnDone.AnimationSpeed = 200;
            this.btnDone.AutoGenerateColors = false;
            this.btnDone.AutoRoundBorders = false;
            this.btnDone.AutoSizeLeftIcon = true;
            this.btnDone.AutoSizeRightIcon = true;
            this.btnDone.BackColor = System.Drawing.Color.Transparent;
            this.btnDone.BackColor1 = System.Drawing.Color.SeaGreen;
            this.btnDone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDone.BackgroundImage")));
            this.btnDone.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.ButtonText = "Done";
            this.btnDone.ButtonTextMarginLeft = 0;
            this.btnDone.ColorContrastOnClick = 45;
            this.btnDone.ColorContrastOnHover = 45;
            this.btnDone.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnDone.CustomizableEdges = borderEdges12;
            this.btnDone.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDone.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDone.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDone.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDone.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDone.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDone.ForeColor = System.Drawing.Color.White;
            this.btnDone.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDone.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDone.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDone.IconMarginLeft = 11;
            this.btnDone.IconPadding = 10;
            this.btnDone.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDone.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDone.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDone.IconSize = 25;
            this.btnDone.IdleBorderColor = System.Drawing.Color.ForestGreen;
            this.btnDone.IdleBorderRadius = 20;
            this.btnDone.IdleBorderThickness = 1;
            this.btnDone.IdleFillColor = System.Drawing.Color.SeaGreen;
            this.btnDone.IdleIconLeftImage = null;
            this.btnDone.IdleIconRightImage = null;
            this.btnDone.IndicateFocus = false;
            this.btnDone.Location = new System.Drawing.Point(345, 310);
            this.btnDone.Name = "btnDone";
            this.btnDone.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDone.OnDisabledState.BorderRadius = 20;
            this.btnDone.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.OnDisabledState.BorderThickness = 1;
            this.btnDone.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDone.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDone.OnDisabledState.IconLeftImage = null;
            this.btnDone.OnDisabledState.IconRightImage = null;
            this.btnDone.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDone.onHoverState.BorderRadius = 20;
            this.btnDone.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.onHoverState.BorderThickness = 1;
            this.btnDone.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDone.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDone.onHoverState.IconLeftImage = null;
            this.btnDone.onHoverState.IconRightImage = null;
            this.btnDone.OnIdleState.BorderColor = System.Drawing.Color.ForestGreen;
            this.btnDone.OnIdleState.BorderRadius = 20;
            this.btnDone.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.OnIdleState.BorderThickness = 1;
            this.btnDone.OnIdleState.FillColor = System.Drawing.Color.SeaGreen;
            this.btnDone.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDone.OnIdleState.IconLeftImage = null;
            this.btnDone.OnIdleState.IconRightImage = null;
            this.btnDone.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDone.OnPressedState.BorderRadius = 20;
            this.btnDone.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.OnPressedState.BorderThickness = 1;
            this.btnDone.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDone.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDone.OnPressedState.IconLeftImage = null;
            this.btnDone.OnPressedState.IconRightImage = null;
            this.btnDone.Size = new System.Drawing.Size(150, 39);
            this.btnDone.TabIndex = 26;
            this.btnDone.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDone.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDone.TextMarginLeft = 0;
            this.btnDone.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDone.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.bunifuLabel5.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.bunifuLabel5.Location = new System.Drawing.Point(375, 166);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(28, 15);
            this.bunifuLabel5.TabIndex = 27;
            this.bunifuLabel5.Text = "error";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel5.Visible = false;
            // 
            // SetupMoneyWife
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(622, 424);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.btnDone);
            this.Controls.Add(this.btnBackToRegister);
            this.Controls.Add(this.bunifuTextBox1);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.txtBank);
            this.Controls.Add(this.txtCash);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.btn100tr);
            this.Controls.Add(this.btn50tr);
            this.Controls.Add(this.btn5tr);
            this.Controls.Add(this.btn1tr);
            this.Controls.Add(this.bunifuLabel1);
            this.Name = "SetupMoneyWife";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Setup your MoneyWife";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private UI.WinForms.BunifuLabel bunifuLabel1;
        private UI.WinForms.BunifuButton.BunifuButton2 btn1tr;
        private UI.WinForms.BunifuButton.BunifuButton2 btn5tr;
        private UI.WinForms.BunifuButton.BunifuButton2 btn50tr;
        private UI.WinForms.BunifuButton.BunifuButton2 btn100tr;
        private UI.WinForms.BunifuLabel bunifuLabel2;
        private UI.WinForms.BunifuLabel bunifuLabel3;
        private UI.WinForms.BunifuTextBox txtCash;
        private UI.WinForms.BunifuTextBox txtBank;
        private UI.WinForms.BunifuLabel bunifuLabel4;
        private UI.WinForms.BunifuTextBox bunifuTextBox1;
        private UI.WinForms.BunifuButton.BunifuButton2 btnBackToRegister;
        private UI.WinForms.BunifuButton.BunifuButton2 btnDone;
        private UI.WinForms.BunifuLabel bunifuLabel5;
    }
}