namespace MoneyWife
{
    partial class SetupMoneyWife
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SetupMoneyWife));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn3so = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn4so = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn5so = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn6so = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtCash = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtBank = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtTotal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnBackToRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnDone = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.bunifuLabel1.Location = new System.Drawing.Point(164, 12);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(336, 45);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "Setup your MoneyWife";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btn3so
            // 
            this.btn3so.AllowAnimations = true;
            this.btn3so.AllowMouseEffects = true;
            this.btn3so.AllowToggling = false;
            this.btn3so.AnimationSpeed = 200;
            this.btn3so.AutoGenerateColors = false;
            this.btn3so.AutoRoundBorders = false;
            this.btn3so.AutoSizeLeftIcon = true;
            this.btn3so.AutoSizeRightIcon = true;
            this.btn3so.BackColor = System.Drawing.Color.Transparent;
            this.btn3so.BackColor1 = System.Drawing.Color.DarkGray;
            this.btn3so.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn3so.BackgroundImage")));
            this.btn3so.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn3so.ButtonText = ".000 VND";
            this.btn3so.ButtonTextMarginLeft = 0;
            this.btn3so.ColorContrastOnClick = 45;
            this.btn3so.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn3so.CustomizableEdges = borderEdges7;
            this.btn3so.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn3so.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn3so.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn3so.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn3so.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn3so.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btn3so.ForeColor = System.Drawing.Color.White;
            this.btn3so.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn3so.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn3so.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn3so.IconMarginLeft = 11;
            this.btn3so.IconPadding = 10;
            this.btn3so.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn3so.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn3so.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn3so.IconSize = 25;
            this.btn3so.IdleBorderColor = System.Drawing.Color.DimGray;
            this.btn3so.IdleBorderRadius = 20;
            this.btn3so.IdleBorderThickness = 1;
            this.btn3so.IdleFillColor = System.Drawing.Color.DarkGray;
            this.btn3so.IdleIconLeftImage = null;
            this.btn3so.IdleIconRightImage = null;
            this.btn3so.IndicateFocus = false;
            this.btn3so.Location = new System.Drawing.Point(14, 73);
            this.btn3so.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btn3so.Name = "btn3so";
            this.btn3so.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn3so.OnDisabledState.BorderRadius = 20;
            this.btn3so.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn3so.OnDisabledState.BorderThickness = 1;
            this.btn3so.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn3so.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn3so.OnDisabledState.IconLeftImage = null;
            this.btn3so.OnDisabledState.IconRightImage = null;
            this.btn3so.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn3so.onHoverState.BorderRadius = 20;
            this.btn3so.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn3so.onHoverState.BorderThickness = 1;
            this.btn3so.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn3so.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn3so.onHoverState.IconLeftImage = null;
            this.btn3so.onHoverState.IconRightImage = null;
            this.btn3so.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.btn3so.OnIdleState.BorderRadius = 20;
            this.btn3so.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn3so.OnIdleState.BorderThickness = 1;
            this.btn3so.OnIdleState.FillColor = System.Drawing.Color.DarkGray;
            this.btn3so.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn3so.OnIdleState.IconLeftImage = null;
            this.btn3so.OnIdleState.IconRightImage = null;
            this.btn3so.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn3so.OnPressedState.BorderRadius = 20;
            this.btn3so.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn3so.OnPressedState.BorderThickness = 1;
            this.btn3so.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn3so.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn3so.OnPressedState.IconLeftImage = null;
            this.btn3so.OnPressedState.IconRightImage = null;
            this.btn3so.Size = new System.Drawing.Size(144, 46);
            this.btn3so.TabIndex = 5;
            this.btn3so.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn3so.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn3so.TextMarginLeft = 0;
            this.btn3so.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn3so.UseDefaultRadiusAndThickness = true;
            this.btn3so.Click += new System.EventHandler(this.btn3so_Click);
            // 
            // btn4so
            // 
            this.btn4so.AllowAnimations = true;
            this.btn4so.AllowMouseEffects = true;
            this.btn4so.AllowToggling = false;
            this.btn4so.AnimationSpeed = 200;
            this.btn4so.AutoGenerateColors = false;
            this.btn4so.AutoRoundBorders = false;
            this.btn4so.AutoSizeLeftIcon = true;
            this.btn4so.AutoSizeRightIcon = true;
            this.btn4so.BackColor = System.Drawing.Color.Transparent;
            this.btn4so.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn4so.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn4so.BackgroundImage")));
            this.btn4so.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn4so.ButtonText = "0.000 VND";
            this.btn4so.ButtonTextMarginLeft = 0;
            this.btn4so.ColorContrastOnClick = 45;
            this.btn4so.ColorContrastOnHover = 45;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn4so.CustomizableEdges = borderEdges8;
            this.btn4so.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn4so.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn4so.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn4so.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn4so.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn4so.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btn4so.ForeColor = System.Drawing.Color.White;
            this.btn4so.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn4so.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn4so.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn4so.IconMarginLeft = 11;
            this.btn4so.IconPadding = 10;
            this.btn4so.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn4so.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn4so.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn4so.IconSize = 25;
            this.btn4so.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btn4so.IdleBorderRadius = 20;
            this.btn4so.IdleBorderThickness = 1;
            this.btn4so.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn4so.IdleIconLeftImage = null;
            this.btn4so.IdleIconRightImage = null;
            this.btn4so.IndicateFocus = false;
            this.btn4so.Location = new System.Drawing.Point(164, 73);
            this.btn4so.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btn4so.Name = "btn4so";
            this.btn4so.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn4so.OnDisabledState.BorderRadius = 20;
            this.btn4so.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn4so.OnDisabledState.BorderThickness = 1;
            this.btn4so.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn4so.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn4so.OnDisabledState.IconLeftImage = null;
            this.btn4so.OnDisabledState.IconRightImage = null;
            this.btn4so.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn4so.onHoverState.BorderRadius = 20;
            this.btn4so.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn4so.onHoverState.BorderThickness = 1;
            this.btn4so.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn4so.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn4so.onHoverState.IconLeftImage = null;
            this.btn4so.onHoverState.IconRightImage = null;
            this.btn4so.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btn4so.OnIdleState.BorderRadius = 20;
            this.btn4so.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn4so.OnIdleState.BorderThickness = 1;
            this.btn4so.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn4so.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn4so.OnIdleState.IconLeftImage = null;
            this.btn4so.OnIdleState.IconRightImage = null;
            this.btn4so.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn4so.OnPressedState.BorderRadius = 20;
            this.btn4so.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn4so.OnPressedState.BorderThickness = 1;
            this.btn4so.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn4so.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn4so.OnPressedState.IconLeftImage = null;
            this.btn4so.OnPressedState.IconRightImage = null;
            this.btn4so.Size = new System.Drawing.Size(163, 46);
            this.btn4so.TabIndex = 6;
            this.btn4so.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn4so.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn4so.TextMarginLeft = 0;
            this.btn4so.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn4so.UseDefaultRadiusAndThickness = true;
            this.btn4so.Click += new System.EventHandler(this.btn4so_Click);
            // 
            // btn5so
            // 
            this.btn5so.AllowAnimations = true;
            this.btn5so.AllowMouseEffects = true;
            this.btn5so.AllowToggling = false;
            this.btn5so.AnimationSpeed = 200;
            this.btn5so.AutoGenerateColors = false;
            this.btn5so.AutoRoundBorders = false;
            this.btn5so.AutoSizeLeftIcon = true;
            this.btn5so.AutoSizeRightIcon = true;
            this.btn5so.BackColor = System.Drawing.Color.Transparent;
            this.btn5so.BackColor1 = System.Drawing.Color.SeaGreen;
            this.btn5so.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn5so.BackgroundImage")));
            this.btn5so.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5so.ButtonText = "00.000 VND";
            this.btn5so.ButtonTextMarginLeft = 0;
            this.btn5so.ColorContrastOnClick = 45;
            this.btn5so.ColorContrastOnHover = 45;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btn5so.CustomizableEdges = borderEdges9;
            this.btn5so.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn5so.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn5so.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn5so.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn5so.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn5so.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btn5so.ForeColor = System.Drawing.Color.White;
            this.btn5so.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn5so.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn5so.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn5so.IconMarginLeft = 11;
            this.btn5so.IconPadding = 10;
            this.btn5so.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn5so.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn5so.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn5so.IconSize = 25;
            this.btn5so.IdleBorderColor = System.Drawing.Color.MediumSeaGreen;
            this.btn5so.IdleBorderRadius = 20;
            this.btn5so.IdleBorderThickness = 1;
            this.btn5so.IdleFillColor = System.Drawing.Color.SeaGreen;
            this.btn5so.IdleIconLeftImage = null;
            this.btn5so.IdleIconRightImage = null;
            this.btn5so.IndicateFocus = false;
            this.btn5so.Location = new System.Drawing.Point(335, 73);
            this.btn5so.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btn5so.Name = "btn5so";
            this.btn5so.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn5so.OnDisabledState.BorderRadius = 20;
            this.btn5so.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5so.OnDisabledState.BorderThickness = 1;
            this.btn5so.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn5so.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn5so.OnDisabledState.IconLeftImage = null;
            this.btn5so.OnDisabledState.IconRightImage = null;
            this.btn5so.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn5so.onHoverState.BorderRadius = 20;
            this.btn5so.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5so.onHoverState.BorderThickness = 1;
            this.btn5so.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn5so.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn5so.onHoverState.IconLeftImage = null;
            this.btn5so.onHoverState.IconRightImage = null;
            this.btn5so.OnIdleState.BorderColor = System.Drawing.Color.MediumSeaGreen;
            this.btn5so.OnIdleState.BorderRadius = 20;
            this.btn5so.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5so.OnIdleState.BorderThickness = 1;
            this.btn5so.OnIdleState.FillColor = System.Drawing.Color.SeaGreen;
            this.btn5so.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn5so.OnIdleState.IconLeftImage = null;
            this.btn5so.OnIdleState.IconRightImage = null;
            this.btn5so.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn5so.OnPressedState.BorderRadius = 20;
            this.btn5so.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn5so.OnPressedState.BorderThickness = 1;
            this.btn5so.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn5so.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn5so.OnPressedState.IconLeftImage = null;
            this.btn5so.OnPressedState.IconRightImage = null;
            this.btn5so.Size = new System.Drawing.Size(175, 46);
            this.btn5so.TabIndex = 7;
            this.btn5so.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn5so.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn5so.TextMarginLeft = 0;
            this.btn5so.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn5so.UseDefaultRadiusAndThickness = true;
            this.btn5so.Click += new System.EventHandler(this.btn5so_Click);
            // 
            // btn6so
            // 
            this.btn6so.AllowAnimations = true;
            this.btn6so.AllowMouseEffects = true;
            this.btn6so.AllowToggling = false;
            this.btn6so.AnimationSpeed = 200;
            this.btn6so.AutoGenerateColors = false;
            this.btn6so.AutoRoundBorders = false;
            this.btn6so.AutoSizeLeftIcon = true;
            this.btn6so.AutoSizeRightIcon = true;
            this.btn6so.BackColor = System.Drawing.Color.Transparent;
            this.btn6so.BackColor1 = System.Drawing.Color.Crimson;
            this.btn6so.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn6so.BackgroundImage")));
            this.btn6so.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn6so.ButtonText = "000.000 VND";
            this.btn6so.ButtonTextMarginLeft = 0;
            this.btn6so.ColorContrastOnClick = 45;
            this.btn6so.ColorContrastOnHover = 45;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btn6so.CustomizableEdges = borderEdges10;
            this.btn6so.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn6so.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn6so.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn6so.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn6so.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn6so.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btn6so.ForeColor = System.Drawing.Color.White;
            this.btn6so.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn6so.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn6so.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn6so.IconMarginLeft = 11;
            this.btn6so.IconPadding = 10;
            this.btn6so.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn6so.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn6so.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn6so.IconSize = 25;
            this.btn6so.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btn6so.IdleBorderRadius = 20;
            this.btn6so.IdleBorderThickness = 1;
            this.btn6so.IdleFillColor = System.Drawing.Color.Crimson;
            this.btn6so.IdleIconLeftImage = null;
            this.btn6so.IdleIconRightImage = null;
            this.btn6so.IndicateFocus = false;
            this.btn6so.Location = new System.Drawing.Point(517, 73);
            this.btn6so.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btn6so.Name = "btn6so";
            this.btn6so.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn6so.OnDisabledState.BorderRadius = 20;
            this.btn6so.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn6so.OnDisabledState.BorderThickness = 1;
            this.btn6so.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn6so.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn6so.OnDisabledState.IconLeftImage = null;
            this.btn6so.OnDisabledState.IconRightImage = null;
            this.btn6so.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn6so.onHoverState.BorderRadius = 20;
            this.btn6so.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn6so.onHoverState.BorderThickness = 1;
            this.btn6so.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn6so.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn6so.onHoverState.IconLeftImage = null;
            this.btn6so.onHoverState.IconRightImage = null;
            this.btn6so.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btn6so.OnIdleState.BorderRadius = 20;
            this.btn6so.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn6so.OnIdleState.BorderThickness = 1;
            this.btn6so.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btn6so.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn6so.OnIdleState.IconLeftImage = null;
            this.btn6so.OnIdleState.IconRightImage = null;
            this.btn6so.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn6so.OnPressedState.BorderRadius = 20;
            this.btn6so.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn6so.OnPressedState.BorderThickness = 1;
            this.btn6so.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn6so.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn6so.OnPressedState.IconLeftImage = null;
            this.btn6so.OnPressedState.IconRightImage = null;
            this.btn6so.Size = new System.Drawing.Size(187, 46);
            this.btn6so.TabIndex = 8;
            this.btn6so.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn6so.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn6so.TextMarginLeft = 0;
            this.btn6so.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn6so.UseDefaultRadiusAndThickness = true;
            this.btn6so.Click += new System.EventHandler(this.btn6so_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.bunifuLabel2.Location = new System.Drawing.Point(107, 163);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(108, 21);
            this.bunifuLabel2.TabIndex = 9;
            this.bunifuLabel2.Text = "Tiền mặt/Cash:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.bunifuLabel3.Location = new System.Drawing.Point(102, 238);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(115, 21);
            this.bunifuLabel3.TabIndex = 10;
            this.bunifuLabel3.Text = "Tài khoản/Bank:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtCash
            // 
            this.txtCash.AcceptsReturn = false;
            this.txtCash.AcceptsTab = false;
            this.txtCash.AnimationSpeed = 200;
            this.txtCash.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCash.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCash.AutoSizeHeight = true;
            this.txtCash.BackColor = System.Drawing.Color.Transparent;
            this.txtCash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCash.BackgroundImage")));
            this.txtCash.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCash.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCash.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCash.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCash.BorderRadius = 20;
            this.txtCash.BorderThickness = 1;
            this.txtCash.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCash.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.txtCash.DefaultText = "";
            this.txtCash.FillColor = System.Drawing.Color.White;
            this.txtCash.HideSelection = true;
            this.txtCash.IconLeft = null;
            this.txtCash.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.IconPadding = 10;
            this.txtCash.IconRight = null;
            this.txtCash.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.Lines = new string[0];
            this.txtCash.Location = new System.Drawing.Point(240, 144);
            this.txtCash.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.txtCash.MaxLength = 32767;
            this.txtCash.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCash.Modified = false;
            this.txtCash.Multiline = false;
            this.txtCash.Name = "txtCash";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCash.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnIdleState = stateProperties16;
            this.txtCash.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.txtCash.PasswordChar = '\0';
            this.txtCash.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCash.PlaceholderText = "000.000";
            this.txtCash.ReadOnly = false;
            this.txtCash.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCash.SelectedText = "";
            this.txtCash.SelectionLength = 0;
            this.txtCash.SelectionStart = 0;
            this.txtCash.ShortcutsEnabled = true;
            this.txtCash.Size = new System.Drawing.Size(337, 43);
            this.txtCash.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCash.TabIndex = 12;
            this.txtCash.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtCash.TextMarginBottom = 0;
            this.txtCash.TextMarginLeft = 3;
            this.txtCash.TextMarginTop = 1;
            this.txtCash.TextPlaceholder = "000.000";
            this.txtCash.UseSystemPasswordChar = false;
            this.txtCash.WordWrap = true;
            this.txtCash.TextChange += new System.EventHandler(this.txtCash_TextChange);
            this.txtCash.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtCash_KeyPress);
            this.txtCash.Enter += new System.EventHandler(this.txtCash_Enter);
            this.txtCash.Leave += new System.EventHandler(this.txtCash_Leave);
            // 
            // txtBank
            // 
            this.txtBank.AcceptsReturn = false;
            this.txtBank.AcceptsTab = false;
            this.txtBank.AnimationSpeed = 200;
            this.txtBank.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBank.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBank.AutoSizeHeight = true;
            this.txtBank.BackColor = System.Drawing.Color.Transparent;
            this.txtBank.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBank.BackgroundImage")));
            this.txtBank.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtBank.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBank.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtBank.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtBank.BorderRadius = 20;
            this.txtBank.BorderThickness = 1;
            this.txtBank.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBank.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBank.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.txtBank.DefaultText = "";
            this.txtBank.FillColor = System.Drawing.Color.White;
            this.txtBank.HideSelection = true;
            this.txtBank.IconLeft = null;
            this.txtBank.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBank.IconPadding = 10;
            this.txtBank.IconRight = null;
            this.txtBank.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBank.Lines = new string[0];
            this.txtBank.Location = new System.Drawing.Point(240, 216);
            this.txtBank.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.txtBank.MaxLength = 32767;
            this.txtBank.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBank.Modified = false;
            this.txtBank.Multiline = false;
            this.txtBank.Name = "txtBank";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBank.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBank.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBank.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBank.OnIdleState = stateProperties20;
            this.txtBank.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.txtBank.PasswordChar = '\0';
            this.txtBank.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBank.PlaceholderText = "000.000";
            this.txtBank.ReadOnly = false;
            this.txtBank.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBank.SelectedText = "";
            this.txtBank.SelectionLength = 0;
            this.txtBank.SelectionStart = 0;
            this.txtBank.ShortcutsEnabled = true;
            this.txtBank.Size = new System.Drawing.Size(337, 43);
            this.txtBank.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBank.TabIndex = 13;
            this.txtBank.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtBank.TextMarginBottom = 0;
            this.txtBank.TextMarginLeft = 3;
            this.txtBank.TextMarginTop = 1;
            this.txtBank.TextPlaceholder = "000.000";
            this.txtBank.UseSystemPasswordChar = false;
            this.txtBank.WordWrap = true;
            this.txtBank.TextChange += new System.EventHandler(this.txtBank_TextChange);
            this.txtBank.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtBank_KeyPress);
            this.txtBank.Enter += new System.EventHandler(this.txtBank_Enter);
            this.txtBank.Leave += new System.EventHandler(this.txtBank_Leave);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.bunifuLabel4.Location = new System.Drawing.Point(119, 270);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(98, 43);
            this.bunifuLabel4.TabIndex = 14;
            this.bunifuLabel4.Text = "Total money/\r\nTổng tiền:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtTotal
            // 
            this.txtTotal.AcceptsReturn = false;
            this.txtTotal.AcceptsTab = false;
            this.txtTotal.AnimationSpeed = 200;
            this.txtTotal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTotal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTotal.AutoSizeHeight = true;
            this.txtTotal.BackColor = System.Drawing.Color.Transparent;
            this.txtTotal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTotal.BackgroundImage")));
            this.txtTotal.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTotal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTotal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTotal.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTotal.BorderRadius = 20;
            this.txtTotal.BorderThickness = 1;
            this.txtTotal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTotal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotal.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.txtTotal.DefaultText = "";
            this.txtTotal.FillColor = System.Drawing.Color.White;
            this.txtTotal.HideSelection = true;
            this.txtTotal.IconLeft = null;
            this.txtTotal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotal.IconPadding = 10;
            this.txtTotal.IconRight = null;
            this.txtTotal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotal.Lines = new string[0];
            this.txtTotal.Location = new System.Drawing.Point(240, 277);
            this.txtTotal.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.txtTotal.MaxLength = 32767;
            this.txtTotal.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTotal.Modified = false;
            this.txtTotal.Multiline = false;
            this.txtTotal.Name = "txtTotal";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotal.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTotal.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotal.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotal.OnIdleState = stateProperties24;
            this.txtTotal.Padding = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.txtTotal.PasswordChar = '\0';
            this.txtTotal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTotal.PlaceholderText = "000.000";
            this.txtTotal.ReadOnly = true;
            this.txtTotal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTotal.SelectedText = "";
            this.txtTotal.SelectionLength = 0;
            this.txtTotal.SelectionStart = 0;
            this.txtTotal.ShortcutsEnabled = true;
            this.txtTotal.Size = new System.Drawing.Size(337, 43);
            this.txtTotal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTotal.TabIndex = 15;
            this.txtTotal.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtTotal.TextMarginBottom = 0;
            this.txtTotal.TextMarginLeft = 3;
            this.txtTotal.TextMarginTop = 1;
            this.txtTotal.TextPlaceholder = "000.000";
            this.txtTotal.UseSystemPasswordChar = false;
            this.txtTotal.WordWrap = true;
            // 
            // btnBackToRegister
            // 
            this.btnBackToRegister.AllowAnimations = true;
            this.btnBackToRegister.AllowMouseEffects = true;
            this.btnBackToRegister.AllowToggling = false;
            this.btnBackToRegister.AnimationSpeed = 200;
            this.btnBackToRegister.AutoGenerateColors = false;
            this.btnBackToRegister.AutoRoundBorders = false;
            this.btnBackToRegister.AutoSizeLeftIcon = true;
            this.btnBackToRegister.AutoSizeRightIcon = true;
            this.btnBackToRegister.BackColor = System.Drawing.Color.Transparent;
            this.btnBackToRegister.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBackToRegister.BackgroundImage")));
            this.btnBackToRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.ButtonText = "Back";
            this.btnBackToRegister.ButtonTextMarginLeft = 0;
            this.btnBackToRegister.ColorContrastOnClick = 45;
            this.btnBackToRegister.ColorContrastOnHover = 45;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnBackToRegister.CustomizableEdges = borderEdges11;
            this.btnBackToRegister.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBackToRegister.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBackToRegister.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBackToRegister.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBackToRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnBackToRegister.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnBackToRegister.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBackToRegister.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBackToRegister.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBackToRegister.IconMarginLeft = 11;
            this.btnBackToRegister.IconPadding = 10;
            this.btnBackToRegister.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBackToRegister.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBackToRegister.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBackToRegister.IconSize = 25;
            this.btnBackToRegister.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.IdleBorderRadius = 20;
            this.btnBackToRegister.IdleBorderThickness = 1;
            this.btnBackToRegister.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.IdleIconLeftImage = null;
            this.btnBackToRegister.IdleIconRightImage = null;
            this.btnBackToRegister.IndicateFocus = false;
            this.btnBackToRegister.Location = new System.Drawing.Point(127, 358);
            this.btnBackToRegister.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btnBackToRegister.Name = "btnBackToRegister";
            this.btnBackToRegister.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBackToRegister.OnDisabledState.BorderRadius = 20;
            this.btnBackToRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.OnDisabledState.BorderThickness = 1;
            this.btnBackToRegister.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBackToRegister.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBackToRegister.OnDisabledState.IconLeftImage = null;
            this.btnBackToRegister.OnDisabledState.IconRightImage = null;
            this.btnBackToRegister.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBackToRegister.onHoverState.BorderRadius = 20;
            this.btnBackToRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.onHoverState.BorderThickness = 1;
            this.btnBackToRegister.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBackToRegister.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.onHoverState.IconLeftImage = null;
            this.btnBackToRegister.onHoverState.IconRightImage = null;
            this.btnBackToRegister.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.OnIdleState.BorderRadius = 20;
            this.btnBackToRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.OnIdleState.BorderThickness = 1;
            this.btnBackToRegister.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnBackToRegister.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.OnIdleState.IconLeftImage = null;
            this.btnBackToRegister.OnIdleState.IconRightImage = null;
            this.btnBackToRegister.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBackToRegister.OnPressedState.BorderRadius = 20;
            this.btnBackToRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBackToRegister.OnPressedState.BorderThickness = 1;
            this.btnBackToRegister.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBackToRegister.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBackToRegister.OnPressedState.IconLeftImage = null;
            this.btnBackToRegister.OnPressedState.IconRightImage = null;
            this.btnBackToRegister.Size = new System.Drawing.Size(175, 45);
            this.btnBackToRegister.TabIndex = 25;
            this.btnBackToRegister.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBackToRegister.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBackToRegister.TextMarginLeft = 0;
            this.btnBackToRegister.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBackToRegister.UseDefaultRadiusAndThickness = true;
            this.btnBackToRegister.Click += new System.EventHandler(this.btnBackToRegister_Click);
            // 
            // btnDone
            // 
            this.btnDone.AllowAnimations = true;
            this.btnDone.AllowMouseEffects = true;
            this.btnDone.AllowToggling = false;
            this.btnDone.AnimationSpeed = 200;
            this.btnDone.AutoGenerateColors = false;
            this.btnDone.AutoRoundBorders = false;
            this.btnDone.AutoSizeLeftIcon = true;
            this.btnDone.AutoSizeRightIcon = true;
            this.btnDone.BackColor = System.Drawing.Color.Transparent;
            this.btnDone.BackColor1 = System.Drawing.Color.SeaGreen;
            this.btnDone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDone.BackgroundImage")));
            this.btnDone.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.ButtonText = "Done";
            this.btnDone.ButtonTextMarginLeft = 0;
            this.btnDone.ColorContrastOnClick = 45;
            this.btnDone.ColorContrastOnHover = 45;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnDone.CustomizableEdges = borderEdges12;
            this.btnDone.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDone.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDone.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDone.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDone.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDone.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnDone.ForeColor = System.Drawing.Color.White;
            this.btnDone.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDone.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDone.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDone.IconMarginLeft = 11;
            this.btnDone.IconPadding = 10;
            this.btnDone.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDone.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDone.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDone.IconSize = 25;
            this.btnDone.IdleBorderColor = System.Drawing.Color.ForestGreen;
            this.btnDone.IdleBorderRadius = 20;
            this.btnDone.IdleBorderThickness = 1;
            this.btnDone.IdleFillColor = System.Drawing.Color.SeaGreen;
            this.btnDone.IdleIconLeftImage = null;
            this.btnDone.IdleIconRightImage = null;
            this.btnDone.IndicateFocus = false;
            this.btnDone.Location = new System.Drawing.Point(402, 358);
            this.btnDone.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.btnDone.Name = "btnDone";
            this.btnDone.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDone.OnDisabledState.BorderRadius = 20;
            this.btnDone.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.OnDisabledState.BorderThickness = 1;
            this.btnDone.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDone.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDone.OnDisabledState.IconLeftImage = null;
            this.btnDone.OnDisabledState.IconRightImage = null;
            this.btnDone.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDone.onHoverState.BorderRadius = 20;
            this.btnDone.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.onHoverState.BorderThickness = 1;
            this.btnDone.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDone.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDone.onHoverState.IconLeftImage = null;
            this.btnDone.onHoverState.IconRightImage = null;
            this.btnDone.OnIdleState.BorderColor = System.Drawing.Color.ForestGreen;
            this.btnDone.OnIdleState.BorderRadius = 20;
            this.btnDone.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.OnIdleState.BorderThickness = 1;
            this.btnDone.OnIdleState.FillColor = System.Drawing.Color.SeaGreen;
            this.btnDone.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDone.OnIdleState.IconLeftImage = null;
            this.btnDone.OnIdleState.IconRightImage = null;
            this.btnDone.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDone.OnPressedState.BorderRadius = 20;
            this.btnDone.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDone.OnPressedState.BorderThickness = 1;
            this.btnDone.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDone.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDone.OnPressedState.IconLeftImage = null;
            this.btnDone.OnPressedState.IconRightImage = null;
            this.btnDone.Size = new System.Drawing.Size(175, 45);
            this.btnDone.TabIndex = 26;
            this.btnDone.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDone.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDone.TextMarginLeft = 0;
            this.btnDone.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDone.UseDefaultRadiusAndThickness = true;
            this.btnDone.Click += new System.EventHandler(this.btnDone_Click);
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point);
            this.bunifuLabel5.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.bunifuLabel5.Location = new System.Drawing.Point(545, 188);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(28, 15);
            this.bunifuLabel5.TabIndex = 27;
            this.bunifuLabel5.Text = "error";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel5.Visible = false;
            // 
            // SetupMoneyWife
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(726, 489);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.btnDone);
            this.Controls.Add(this.btnBackToRegister);
            this.Controls.Add(this.txtTotal);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.txtBank);
            this.Controls.Add(this.txtCash);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.btn6so);
            this.Controls.Add(this.btn5so);
            this.Controls.Add(this.btn4so);
            this.Controls.Add(this.btn3so);
            this.Controls.Add(this.bunifuLabel1);
            this.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            this.Name = "SetupMoneyWife";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Setup your MoneyWife";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.SetupMoneyWife_FormClosed);
            this.Load += new System.EventHandler(this.SetupMoneyWife_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn3so;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn4so;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn5so;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn6so;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txtCash;
        private Bunifu.UI.WinForms.BunifuTextBox txtBank;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox txtTotal;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnBackToRegister;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDone;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
    }
}